from sqlalchemy import delete, select, text
from sqlalchemy.orm import Session
import tiktoken

from app.models.document_chunk import DocumentChunk


class ChunkRepository:
    def __init__(self, db: Session):
        self.db = db
        self.encoding = tiktoken.get_encoding("cl100k_base")

    def save_chunks(
        self,
        document_id: str,
        chunks: list[str],
    ) -> list[DocumentChunk]:

        chunk_objects = []

        for index, content in enumerate(chunks):
            chunk_objects.append(
                DocumentChunk(
                    document_id=document_id,
                    chunk_index=index,
                    content=content,
                    token_count=len(
                        self.encoding.encode(content)
                    ),
                )
            )

        self.db.add_all(chunk_objects)
        self.db.flush()

        # Populate UUIDs generated by SQLAlchemy.
        for chunk in chunk_objects:
            self.db.refresh(chunk)

        # Add chunks to SQLite FTS5 index.
        for chunk in chunk_objects:
            rowid = self.db.execute(
                text(
                    """
                    SELECT rowid
                    FROM document_chunks
                    WHERE id = :id
                    """
                ),
                {
                    "id": chunk.id,
                },
            ).scalar_one()

            self.db.execute(
                text(
                    """
                    INSERT INTO document_chunks_fts(
                        rowid,
                        content
                    )
                    VALUES (
                        :rowid,
                        :content
                    )
                    """
                ),
                {
                    "rowid": rowid,
                    "content": chunk.content,
                },
            )

        return chunk_objects

    def get_chunks_by_ids(
        self,
        chunk_ids: list[str],
    ) -> list[DocumentChunk]:

        if not chunk_ids:
            return []

        stmt = (
            select(DocumentChunk)
            .where(DocumentChunk.id.in_(chunk_ids))
        )

        return list(
            self.db.scalars(stmt).all()
        )

    def delete_by_document_id(
        self,
        document_id: str,
    ) -> None:

        chunks = self.db.scalars(
            select(DocumentChunk).where(
                DocumentChunk.document_id == document_id
            )
        ).all()

        # Remove chunks from FTS5 first.
        for chunk in chunks:
            rowid = self.db.execute(
                text(
                    """
                    SELECT rowid
                    FROM document_chunks
                    WHERE id = :id
                    """
                ),
                {
                    "id": chunk.id,
                },
            ).scalar_one()

            self.db.execute(
                text(
                    """
                    INSERT INTO document_chunks_fts(
                        document_chunks_fts,
                        rowid,
                        content
                    )
                    VALUES (
                        'delete',
                        :rowid,
                        :content
                    )
                    """
                ),
                {
                    "rowid": rowid,
                    "content": chunk.content,
                },
            )

        # Delete chunks from SQLite.
        stmt = (
            delete(DocumentChunk)
            .where(
                DocumentChunk.document_id == document_id
            )
        )

        self.db.execute(stmt)

    def keyword_search(
        self,
        query: str,
        top_k: int = 10,
        document_id: str | None = None,
    ) -> list[DocumentChunk]:

        if not query.strip():
            return []

        # Keep only words that FTS5 can search safely.
        words = [
            word
            for word in query.split()
            if word.isalnum()
        ]

        if not words:
            return []

        # Search terms individually so natural-language
        # questions don't cause FTS5 syntax errors.
        fts_query = " OR ".join(
            f'"{word}"'
            for word in words
        )

        if document_id is None:
            rows = self.db.execute(
                text(
                    """
                    SELECT
                        rowid,
                        bm25(document_chunks_fts) AS score
                    FROM document_chunks_fts
                    WHERE document_chunks_fts MATCH :query
                    ORDER BY score
                    LIMIT :limit
                    """
                ),
                {
                    "query": fts_query,
                    "limit": top_k,
                },
            ).fetchall()

        else:
            rows = self.db.execute(
                text(
                    """
                    SELECT
                        f.rowid,
                        bm25(f) AS score
                    FROM document_chunks_fts AS f
                    JOIN document_chunks AS c
                        ON c.rowid = f.rowid
                    WHERE f MATCH :query
                      AND c.document_id = :document_id
                    ORDER BY score
                    LIMIT :limit
                    """
                ),
                {
                    "query": fts_query,
                    "document_id": document_id,
                    "limit": top_k,
                },
            ).fetchall()

        if not rows:
            return []

        rowids = [row[0] for row in rows]

        # Fetch chunks using SQLite rowids.
        chunk_rows = self.db.execute(
            text(
                """
                SELECT id
                FROM document_chunks
                WHERE rowid IN (
                    SELECT value
                    FROM json_each(:rowids)
                )
                """
            ),
            {
                "rowids": str(rowids).replace("'", '"'),
            },
        ).fetchall()

        chunk_ids = [
            row[0]
            for row in chunk_rows
        ]

        chunks = self.get_chunks_by_ids(chunk_ids)

        chunk_lookup = {
            chunk.id: chunk
            for chunk in chunks
        }

        # Preserve FTS ranking.
        rowid_to_chunk = {}

        for rowid in rowids:
            chunk_id_row = self.db.execute(
                text(
                    """
                    SELECT id
                    FROM document_chunks
                    WHERE rowid = :rowid
                    """
                ),
                {
                    "rowid": rowid,
                },
            ).first()

            if chunk_id_row:
                chunk = chunk_lookup.get(
                    chunk_id_row[0]
                )

                if chunk:
                    rowid_to_chunk[rowid] = chunk

        results = []

        for rowid in rowids:
            chunk = rowid_to_chunk.get(rowid)

            if chunk:
                results.append(chunk)

        return results