import tiktoken

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.document_chunk import DocumentChunk


class ChunkRepository:
    def __init__(self, db: Session):
        self.db = db
        self.encoding = tiktoken.get_encoding("cl100k_base")

    def save_chunks(
        self,
        document_id: str,
        chunks: list[str],
    ) -> list[DocumentChunk]:

        chunk_objects = []

        for index, content in enumerate(chunks):
            chunk_objects.append(
                DocumentChunk(
                    document_id=document_id,
                    chunk_index=index,
                    content=content,
                    token_count=len(
                        self.encoding.encode(content)
                    ),
                )
            )

        self.db.add_all(chunk_objects)
        self.db.commit()

        # Populate UUIDs generated by SQLAlchemy
        for chunk in chunk_objects:
            self.db.refresh(chunk)

        return chunk_objects

    def get_chunks_by_ids(
        self,
        chunk_ids: list[str],
    ) -> list[DocumentChunk]:

        stmt = (
            select(DocumentChunk)
            .where(DocumentChunk.id.in_(chunk_ids))
        )

        return list(
            self.db.scalars(stmt).all()
        )